# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_html', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='travel_html.User'),
        ),
    ]
