# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_html', '0002_auto_20161213_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Guest',
            field=models.ManyToManyField(related_name='guest', to='travel_html.User'),
        ),
    ]
